### ISSUE TITLE
Support for different CFA patterns

### ISSUE THREAD

**Issue by tvercaut** [Jamy-L/Handheld-Multi-Frame-Super-Resolution#26]
Thanks for the nice work. It looks like the assumption of a standard 2x2 Bayer filter is assumed. Are there any plans to relax that assumption to work with other configurations such as [Quad-CFA](https://en.wikipedia.org/wiki/Bayer_filter#Modifications)?

Some mobile phones (e.g. Xiaomi Mi 10 Ultra) are now equipped with such sensors.

Single samples (no burst) can be found here:
https://github.com/darktable-org/rawspeed/issues/256
https://drive.google.com/drive/folders/1EPZEpvBHupHehsYI600f9cS7m_MaVhSQ?usp=sharing

**Comment by Jamy-L** [comment]
Hi and thank you for your interest in the project. Adding other array configurations is not planned because I think it would make the code less readable and would diverge too much from the paper.

However it is totally do-able and I encourage you to propose a fork if you feel like it may be useful. The key to make it work are :
- In `merge.py`, one should change the 2 in `local_CFA[pixel_idy%2, pixel_idx%2]` by the size of the pattern (4 for quad CFA).
- The function `compute_grey_image` in `utils_image.py` should still work when using the FFT because it does not uses the pattern, but I have no idea of how good the obtained grey image will look. In decimation mode, the way to obtain a grey image must be modified to work with the new pattern
- `compute_guide_image` in `robustness.py` should be adapted. We currently get the rgb image by decimating bayer quads and averaging the greens, but with a different pattern it should be different.

In the end, it all boils down to figuring out how to decimate a raw image to grey or to rgb with the new pattern. The easiest may be nearest neighbour intepolation for each color channel separately, then averaging to grey.

**Comment by tvercaut** [comment]
Many thanks for the fast response. As there are no current plans for it, I'll close this issue but would re-open it if/when we have any progress to share on our side.

**Comment by sashko5l** [comment]
With help of Claude I was able to adapt the code of the latest release 1.3.2 to work with converted Fuji X-trans DNGs (from X-H2S camera model) which has a very different CFA pattern.

Summary of changes is in attached word doc and more details in this Claude exchange:
https://claude.ai/share/ddb44567-a07e-4dcd-8628-f0ff61fbff09

Should be helpful as a guide on how to adapt to ofther CFA patterns.

[xtrans_changes.docx](https://github.com/user-attachments/files/25753904/xtrans_changes.docx)
