### ISSUE TITLE
Noise curves instead of alpha/beta params ? 

### ISSUE THREAD

**Issue by ardaboluk** [Jamy-L/Handheld-Multi-Frame-Super-Resolution#38]
Hello Jamy

[This](https://www.ipol.im/pub/art/2013/45/) method doesn't give alpha and beta parameters, but gives mean curve and std curve instead. 

In run_fast_MC method alpha and beta parameters are used in calculation of std curve and mean difference curve if I understand right.

Can I use mean and std curves ? Magnitudes and number of sampling points on the curves that are returned by run_fast_MC are wildly different.

**Comment by Jamy-L** [comment]
Hi,

You can estimate alpha and beta from the std curve by expressing $std^2$ as $\alpha \times mean + \beta$, using a linear regression tool for example (Just make sure that mean and std are expressed for an image normalised between 0 and 1).

In theory, the std curve estimated using the Ponomarenko method could directly be used in the main algorithm, instead of simulating the curve based on alpha. The advantage of the Monte Carlo simulation is that we can have a rough estimation for any brightness, and the positions and number of the samples is consistant.

**Comment by ardaboluk** [comment]
Thank you !!
